sudo: false
language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.3
  - 2.3.1
  - 2.4.1

addons:
  code_climate:
    repo_token: 1c269914bbd66d1c3524fd9c13991b82d92b2902701a921954b97fbdd334df3d

before_install: gem install bundler -v 1.14.6

cache:
  - bundler

script:
  - bundle exec rake spec

after_success:
  - bundle exec codeclimate-test-reporter
