sudo: false
language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.3
  - 2.3.1
  - 2.4.1

addons:
  code_climate:
    repo_token: f686acf817e86f278388409d0c049469a50c4dd45ae57449ae0a49abf42fe502

before_install: gem install bundler -v 1.14.6

cache:
  - bundler

script:
  - bundle exec rake spec

after_success:
  - bundle exec codeclimate-test-reporter
